# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 797b9601e718bd957c01e4f5877efd312fa810031f692d1b6f6c326b84b0ea9a2ce7de74f32a40cb23a75d3682c696d498d1b0c5097f99eabef60f13a9596dd2

test:
  secret_key_base: e9ad5476335f2b31a9ada35277862fdfe0c62cb3ba15e6ce9a81768226f69c08589ade08b234bfa0b821f25d70d99153f3bb90634fe2cf5785026276eb314fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
